name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정 UTC 기준 (한국시간 오전 9시)
  workflow_dispatch: # 수동 실행도 가능

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/원본유저명/원본레포.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories || echo "No changes to merge"

      - name: Push changes
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git main
